site_name: Ersatztv-Filler Docs
theme:
  name: material
nav:
  - Home: index.md
  - Installation:
    - Installation: install/install.md
    - Docker: install/docker.md
    - Windows: install/windows.md
    - Mac: install/mac.md
    - Linux: install/linux.md
  - Filler Types:
    - Weather: filler-types/weather.md
    - News: filler-types/news.md
    - Channel Offline: filler-types/channel-offline.md
    - XMLTV Merge: filler-types/xmltv-merge.md
    - Vanity Cards: filler-types/vanity-cards.md
  - Configuration:
    - Configuration: configure/configure.md
    - General Configuration: configure/general.md
    - Weather Configuration: configure/weather.md
    - News Configuration: configure/news.md
    - Channel Offline Configuration: configure/channel-offline.md
    - XMLTV Merge Configuration: configure/xmltv-merge.md
    - Vanity Cards Configuration: configure/vanity-cards.md
  - Themes:
    - Themes: themes/themes.md
  - API:
    - API Subpage 3: folder2/api_subpage3.md
    - API Subpage 4: folder2/api_subpage4.md
  - Development:
    - Development: development/development.md
