site_name: Ersatztv-Filler Docs
theme:
  name: material
  palette:

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

  logo: images/ersatztv-square-logo.png
  favicon: images/favicon-32x32.png
  features:
    - navigation.expand
copyright: Copyright &copy; 2022 - 2023 Liam Robson
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/x4Nk4sfgSg
      name: ErsatzTV-Filler on Discord
    - icon: fontawesome/brands/github
      link: https://github.com/liam8888999/ErsatzTV-Filler
      name: ErsatzTV-Filler on GitHub
    - icon: fontawesome/regular/heart
      link: https://ko-fi.com/E1E4MI8T5
      name: Download on Ko-Fi
    - icon: fontawesome/brands/paypal
      link: https://www.paypal.me/200333
      name: Donate on PayPal
nav:
  - Home: index.md
  - Installation:
    - Installation: install/install.md
    - Docker: install/docker.md
    - Windows: install/windows.md
    - Mac: install/mac.md
    - Linux: install/linux.md
  - Filler Types:
    - Weather: filler-types/weather.md
    - News: filler-types/news.md
    - Channel Offline: filler-types/channel-offline.md
    - XMLTV Merge: filler-types/xmltv-merge.md
    - Vanity Cards: filler-types/vanity-cards.md
  - Configuration:
    - Configuration: configure/configure.md
    - General Configuration: configure/general.md
    - Weather Configuration: configure/weather.md
    - News Configuration: configure/news.md
    - Channel Offline Configuration: configure/channel-offline.md
    - XMLTV Merge Configuration: configure/xmltv-merge.md
    - Vanity Cards Configuration: configure/vanity-cards.md
  - Themes:
    - Themes: themes/themes.md
  - API:
    - API Subpage 3: folder2/api_subpage3.md
    - API Subpage 4: folder2/api_subpage4.md
  - Development:
    - Development: development/development.md
